spring:
  application:
    name: yu-ai-code-mother-backend
server:
  port: 8081
  servlet:
    context-path: /api
  # knfie4j
    # knife4j
    knife4j:
      enable: true
      setting:
        language: zh_cn

